export enum IconName {
  CART = 'cart',
  PHONE = 'phone',
  USER = 'user',
  UNVISIBLE = 'unvisible',
  VISIBLE = 'visible',
  SEARCH = 'search',
  EMAIL = 'mail',
  WHATSUP = 'whatsup',
  EXIT = 'exit',
  FAVORITE = 'favorite',
  EDIT = 'edit',
  DELETE = 'delete',
  COPY = 'copy',
}
