name: eCommerce-Application

on:
  push:
    branches:
      - feat/sprint_2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: | 
          ${{ runner.os }}-node-


    - name: Install dependencies
      run: npm ci  
    
    - name: Set homepage for GitHub Pages
      run: echo "PUBLIC_URL=https://helgazhizhka.github.io/eCommerce-Application" >> .env
    
    - name: ES Lint
      run: npm run eslint

    - name: Build React app
      env:
        REACT_APP_PROJECT_KEY_CLIENT: ${{ secrets.REACT_APP_PROJECT_KEY_CLIENT }}
        REACT_APP_CLIENT_ID_CLIENT: ${{ secrets.REACT_APP_CLIENT_ID_CLIENT }}
        REACT_APP_CLIENT_SECRET_CLIENT: ${{ secrets.REACT_APP_CLIENT_SECRET_CLIENT }}
        REACT_APP_AUTH_URL_CLIENT: ${{ secrets.REACT_APP_AUTH_URL_CLIENT }}
        REACT_APP_API_URL_CLIENT: ${{ secrets.REACT_APP_API_URL_CLIENT }}
        REACT_APP_SCOPES_CLIENT: ${{ secrets.REACT_APP_SCOPES_CLIENT }}
        REACT_APP_DEPLOY_HOMEPAGE: ${{ secrets.REACT_APP_DEPLOY_HOMEPAGE }}
        GENERATE_SOURCEMAP: false

      run: npm run build  

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: build
        token: ${{ secrets.DEPLOY_TOKEN }}
        clean: true
